"""empty message

Revision ID: 2173b4c8457e
Revises: 91ba3331d5f7
Create Date: 2023-02-14 14:53:42.165571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2173b4c8457e'
down_revision = '91ba3331d5f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
