"""empty message

Revision ID: 4febdd3e2e45
Revises: 2173b4c8457e
Create Date: 2023-02-15 17:48:23.404953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4febdd3e2e45'
down_revision = '2173b4c8457e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
