"""empty message

Revision ID: 91ba3331d5f7
Revises: b904edf8a018
Create Date: 2023-02-13 12:03:59.705651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ba3331d5f7'
down_revision = 'b904edf8a018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
