"""empty message

Revision ID: b904edf8a018
Revises: d72a31298d4e
Create Date: 2023-02-13 10:02:25.836621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b904edf8a018'
down_revision = 'd72a31298d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
